spring.application.name=school
spring.datasource.url=jdbc:postgresql://dpg-d78vor6uk2gs73e2rmrg-a:5432/<vidya_mandir_db>
spring.datasource.username=vidya_mandir_db_user
spring.datasource.password=GBg2B2aEnDtfMqEOwy5tRfc5a2wNCrmm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}